### ISSUE TITLE
Auto-subs dialog doesnt pop up

### ISSUE THREAD

**Issue by attfarkassk** [tmoroney/auto-subs#83]
Have try to solve this with all of the advices i found here - adding python to path, downgrading to python 3.10, verifying that python version is same (and only) for auto-subs as for DaVinci, removing/modifying certain strings in auto-subs.py - nothing works. In the console still getting:

Traceback (most recent call last):
  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Fusion\Scripts\Utility\auto-subs.py", line 26, in <module>
    import stable_whisper
  File "D:\Users\attila\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_whisper\__init__.py", line 1, in <module>
    from .stabilization import *
  File "D:\Users\attila\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_whisper\stabilization.py", line 6, in <module>
    from whisper.tokenizer import Tokenizer
  File "D:\Users\attila\AppData\Local\Programs\Python\Python310\lib\site-packages\whisper\__init__.py", line 12, in <module>
    from .decoding import DecodingOptions, DecodingResult, decode, detect_language
  File "D:\Users\attila\AppData\Local\Programs\Python\Python310\lib\site-packages\whisper\decoding.py", line 11, in <module>
    from .tokenizer import Tokenizer, get_tokenizer
  File "D:\Users\attila\AppData\Local\Programs\Python\Python310\lib\site-packages\whisper\tokenizer.py", line 8, in <module>
    from transformers import GPT2TokenizerFast
  File "D:\Users\attila\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "D:\Users\attila\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "D:\Users\attila\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "D:\Users\attila\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\generic.py", line 32, in <module>
    from .import_utils import (
  File "D:\Users\attila\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py", line 37, in <module>
    logger = logging.get_logger(__name__)  # pylint: disable=invalid-name
  File "D:\Users\attila\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\logging.py", line 157, in get_logger
    _configure_library_root_logger()
  File "D:\Users\attila\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\logging.py", line 93, in _configure_library_root_logger
    _default_handler.flush = sys.stderr.flush
AttributeError: module 'fu_stderr' has no attribute 'flush'

Any suggestions what should i do to get it work?
Thanks in advance

**Comment by attfarkassk** [comment]
Sorte out via install-script
